---

-  hosts: all
   tasks:
   - name: Update all machines
     tags: update
     yum:
       update_only: yes
     when: ansible_distribution == "CentOS"

-  hosts: local_c2
   tasks:
   - name: install snapd package
     tags: snapd
     yum:
       name: snapd
     when: ansible_distribution == "CentOS"
   
   - name: install unzip, it is a must, so that terraform can function
     tags: zipping
     package:
       name: unzip

   - name: installing terraform
     tags: zipping
     unarchive:
       src: https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       owner: root
       group: root
       mode: 0755

-  hosts: local_c3
   tasks:
   - name: install nmap
     tags: centos
     yum:
       name: nmap
       state: latest
     when: ansible_distribution == "CentOS"

   - name: copying from repo to c3 machine
     tags: copy
     copy:
       src: sample.txt
       dest: /var/local/sample.txt
       owner: root
       group: root
       mode: 0644


   - name: install mariadb package on CentOS
     tags: centos,mariadb
     yum:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "CentOS"


   - name: install package on Ubuntu
     tags: mariadb,ubuntu
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
